Add Twitter OAuth2 provider
laravel/socialite pull request #574
Opened 2022-01-23 10:09 UTC by dehbka

Unfortunately, at the moment the endpoint for receiving email (https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/manage-account-settings/api-reference/get-account-verify_credentials) has not been to the twitter v2 api.

https://developer.twitter.com/en/docs/twitter-api/migrate/twitter-api-endpoint-map

2022-01-24 09:00 UTC, driesvints requested changes

2022-01-24 17:02 UTC, taylorotwell commented
Converting to draft while Dries' requested changes are made.

2022-01-24 19:54 UTC, merged

2022-01-24 19:57 UTC, taylorotwell commented
@dehbka so, how would you actually use this? `Socialite::driver('twitter-oauth-2')`?

2022-01-24 20:22 UTC, dehbka commented
yeap

> @dehbka so, how would you actually use this? `Socialite::driver('twitter-oauth-2')`?

2022-02-04 13:45 UTC, michaeldyrynda commented
@dehbka did you run into any issues with this?

Seems as though if you have a confidential client (web app or automated bot), you _also_ need to send a basic auth header with the client ID and secret as username and password. 

Not doing so results in authorisation failures when attempting to get a oauth token/fetching the authenticated user. 

It does seem as though you can send the authorisation head for either public or confidential clients, so it may be sufficient to override the `getAccessTokenResponse` method on the `TwitterProvider`  

Happy to send a PR for this, I spent longer than I care to admit trying to figure out why it wasn’t working 🥲

2022-04-20 01:36 UTC, ahmedsayedabdelsalam commented
I know it's not related to laravel it might be permission or something, but i have little question if anyone can help
I was using 'twitter' driver for oauth1 and switched to 'twitter-oauth-2' but the user email now returns 'null'.